version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio_api
    depends_on:
      db:
        condition: service_started
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      - upload-data:/app/uploads
    command: sh -c "npx prisma migrate deploy && node src/index.js"
    networks:
      - desafio-net

  db:
    image: postgres:15
    container_name: desafio_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: desafioTecnico
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - desafio-net

volumes:
  pgdata:
  upload-data:

networks:
  desafio-net: